### PR TITLE
don't pass verbose to caporal

### LINKED ISSUE #131: Error using --verbose with kamus-cli: [TypeError: Cannot convert undefined or null to object]
Getting an error using --verbose with kamus-cli:

    $ kamus-cli  encrypt --verbose --secret mysecret --service-account default --namespace kube-system --kamus-url http://localhost:8080
    /usr/local/lib/node_modules/@soluto-asurion/kamus-cli/node_modules/caporal/lib/program.js:179
        Object.keys(logger.transports).forEach(t => logger.transports[t].level = level)
               ^

    TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)
        at Program._changeLogLevel (/usr/local/lib/node_modules/@soluto-asurion/kamus-cli/node_modules/caporal/lib/program.js:179:12)
        at Program._run (/usr/local/lib/node_modules/@soluto-asurion/kamus-cli/node_modules/caporal/lib/program.js:159:12)
        at Program.parse (/usr/local/lib/node_modules/@soluto-asurion/kamus-cli/node_modules/caporal/lib/program.js:276:17)
        at Object.<anonymous> (/usr/local/lib/node_modules/@soluto-asurion/kamus-cli/lib/index.js:39:6)
        at Module._compile (internal/modules/cjs/loader.js:799:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
        at Module.load (internal/modules/cjs/loader.js:666:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
        at Function.Module._load (internal/modules/cjs/loader.js:598:3)
        at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
        at internal/main/run_main_module.js:21:11

However, if I don't use --verbose, the error is different:

    [info  kamus-cli]: Encryption started...
    [info  kamus-cli]: service account: default
    [info  kamus-cli]: namespace: kube-system
    [warn  kamus-cli]: Auth options were not provided, will try to encrypt without authentication to kamus
    Handling connection for 8080
    [error kamus-cli]: Error while trying to encrypt with kamus: Encrypt request failed due to unexpected error. Status code: 400

### PR DESCRIPTION
**Pull request by shaikatz**
Closes #131 

caporal, our CLI manager, requires winston compatible logger, and we use ColorfulChalkLogger which isn't.
If we pass the `--verbose` parameter to `caporal` we receive an error.

ColorfulChalkLogger generates beautiful outputs and we currently don't want to replace it, this is a workaround to prevent caporal from getting the `--verbose` parameter.

### CODE REVIEW

File: cli/lib/index.js [hunk 1]
```diff
@@ -13,6 +13,11 @@ const logger = new ColorfulChalkLogger('kamus-cli', {
   colorful: true, // the default value is true.
 }, process.argv);
 
+// ColorfulChalkLogger takes care of the verbosity, we don't want to pass it to caporal
+if (process.argv.indexOf('--verbose')) {
```
Comment (omerlh) [inline cli/lib/index.js]: Maybe we need to remove that also from the help? Is that possible?

Comment (shaikatz) [reply cli/lib/index.js]: `--verbose` is still operational, we just take care of that in the `ColorfulChalkLogger` and not in caporal.

Comment (shaikatz) [reply cli/lib/index.js]: You have a point here, we can't remove the --verbose since it's internal to caporal, but we can set the `--log-level` of `ColorfulChalkLogger` to `verbose` when users set it.
I'll add a commit.

**Comment by shaikatz** [comment]
@omerlh Can you take another look?
I've decided to drop `--log-levels` support and use only the `--verbose` which set the logger to debug.
Also, added some debug logs.

File: cli/lib/index.js [hunk 2]
```diff
@@ -5,14 +5,24 @@ const prog = require('caporal');
 const encrypt = require('./actions/encrypt');
 const regexGuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
 
-const { ColorfulChalkLogger, DEBUG } = require('colorful-chalk-logger');
- 
+const { ColorfulChalkLogger, INFO } = require('colorful-chalk-logger');
+
+// translate to ColorfulChalkLogger log level
+if (process.argv.indexOf('--verbose')) {
+  process.argv = process.argv.filter(arg => arg != '--verbose');
```
Comment (omerlh) [inline cli/lib/index.js]: Hacky, but nice!

File: cli/lib/index.js [hunk 3]
```diff
@@ -31,7 +41,6 @@ prog
   .option('--secret-file-encoding <fileEncoding>', 'Encoding of secret file', prog.STRING)
   .option('-o, --output <outputFile>', 'Output to file', prog.STRING)
   .option('-O, --overwrite', 'Overwrites file if it already exists', prog.BOOL)
-  .option('--log-level <debug|verbose|info|warn|error|fatal>', 'log level', prog.STRING)
```
Comment (omerlh) [inline cli/lib/index.js]: Why did you removed this one?

File: cli/lib/index.js (hunk 2 above)
Comment (shaikatz) [reply cli/lib/index.js]: Since we can't delete `--verbose` from caporal, I've decided to drop the `--log-levels`, otherwise it'll be very confusing to have 2 settings from log levels.

File: cli/lib/index.js (hunk 3 above)
Comment (shaikatz) [reply cli/lib/index.js]: Since we can't delete `--verbose` from caporal, I've decided to drop the `--log-levels`, otherwise, it'll be very confusing to have 2 settings from log levels.

File: cli/lib/index.js [hunk 4]
```diff
@@ -7,21 +7,11 @@ const regexGuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[
...
-
 const logger = new ColorfulChalkLogger('kamus-cli', {
   level: INFO,
   date: false,
   colorful: true, 
-}, process.argv);
-
-// remove the log levels before running caporal
-process.argv = process.argv.filter(x => (x != '--log-level' && x != 'debug'));
+}, process.argv.indexOf('--verbose') > -1 ? process.argv.concat(new ['--log-level', 'debug']) : process.argv); // translate to ColorfulChalkLogger log level
```
Comment (omerlh) [inline cli/lib/index.js]: Better!
