### PR TITLE
Fix a bug - now decryptor isAlive is working

### LINKED ISSUE #91: Bug - decryptor api is Alive return 500
There is a bug with token review implemention, results in kubernetes client throwing an exception.

### PR DESCRIPTION
**Pull request by omerlh**
close #91 

Rethinking about that - I think this should be moved to readiness probe, WDYT?

### CODE REVIEW

File: src/decrypt-api/Controllers/MonitoringController.cs [hunk 1]
```diff
@@ -6,38 +6,71 @@
...
+                        }
                     }
-                }
-            });
-
-            return result.Status.Allowed;
-        }
+                });
 
+                return result.Status.Allowed;
```
Comment (shaikatz) [inline src/decrypt-api/Controllers/MonitoringController.cs]: Maybe print some warning if result is not allowed?
